<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
               <form>
                <div class="alert alert-block alert-warning">
                  <h4>Recupere sua Senha</h4>
                  Um link de redefinição será enviado para seu email
                </div>
                      <div class="form-group">
                     <label for="username"> Usuário:</label>
                        <input type="text" name="username" class="form-control" id="username"  placeholder=" Username">
                      </div>
                      <button type="submit" class="btn btn-success">Enviar Link de redefinição</button>
                </form>
            </div>
        </div>
    </div>
</div>
