<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
               <form>
                      <div class="form-group">
                     <label for="username"> Usuário:</label>
                        <input type="text" name="username" class="form-control" id="username"  placeholder=" Username">
                      </div>
                      <div class="form-group">
                      <label for="password"> Senha :</label>
                        <input type="text" name="password" class="form-control" id="password"  placeholder="Sua senha">
                      </div>
                    
                      <button type="submit" class="btn btn-success">Entrar</button>
                </form>
            </div>
        </div>
    </div>
</div>
